#!/bin/bash
# context-monitor.sh — Context window capacity monitor for CIC agents.
# Source: https://github.com/yurukusa/claude-code-hooks/blob/main/hooks/context-monitor.sh (MIT)
# Adapted for CIC: job-specific state files, output path → jobs/<job-id>/output/context-state.md,
#   multi-agent config dir support, CIC evacuation template.
#
# Trigger: PostToolUse (all tools)
# Matcher: "" (every tool invocation)
#
# Graduated warnings: CAUTION(40%) → WARNING(25%) → CRITICAL(20%) → EMERGENCY(15%)
# At CRITICAL/EMERGENCY: writes evacuation template to jobs/<job-id>/output/context-state.md
#
# No-ops silently if CIC_JOB_ID or CIC_WORKDIR is unset.
# Always exits 0 — never blocks the agent.

[ -z "${CIC_JOB_ID:-}" ] && exit 0
[ -z "${CIC_WORKDIR:-}" ] && exit 0

# Job-specific temp files (safe for concurrent jobs)
STATE_FILE="/tmp/cic-ctx-state-${CIC_JOB_ID}"
PCT_FILE="/tmp/cic-ctx-pct-${CIC_JOB_ID}"
COUNTER_FILE="/tmp/cic-ctx-count-${CIC_JOB_ID}"
EVAC_COOLDOWN_FILE="/tmp/cic-ctx-evac-${CIC_JOB_ID}"
EVAC_COOLDOWN_SEC=1800

MISSION_FILE="${CIC_WORKDIR}/jobs/${CIC_JOB_ID}/output/context-state.md"

COUNT=$(cat "$COUNTER_FILE" 2>/dev/null || echo 0)
COUNT=$((COUNT + 1))
echo "$COUNT" > "$COUNTER_FILE"

LAST_STATE=$(cat "$STATE_FILE" 2>/dev/null || echo "normal")

# Check every 3rd invocation; always check at CRITICAL/EMERGENCY
if [ $((COUNT % 3)) -ne 0 ] && [ "$LAST_STATE" != "critical" ] && [ "$LAST_STATE" != "emergency" ]; then
    exit 0
fi

# Extract context % from Claude Code debug logs.
# Checks both default and agent-specific config dirs.
get_context_pct() {
    local debug_dir
    for candidate in "${CLAUDE_CONFIG_DIR:-}" "$HOME/.claude"; do
        [ -z "$candidate" ] && continue
        debug_dir="${candidate}/debug"
        [ -d "$debug_dir" ] || continue

        local latest
        latest=$(find "$debug_dir" -maxdepth 1 -name '*.txt' -printf '%T@ %p\n' 2>/dev/null \
                 | sort -rn | head -1 | cut -d' ' -f2)
        [ -z "$latest" ] && continue

        local line tokens window
        line=$(grep 'autocompact:' "$latest" 2>/dev/null | tail -1)
        [ -z "$line" ] && continue

        tokens=$(echo "$line" | sed 's/.*tokens=\([0-9]*\).*/\1/')
        window=$(echo "$line" | sed 's/.*effectiveWindow=\([0-9]*\).*/\1/')

        if [ -n "$tokens" ] && [ -n "$window" ] && [ "$window" -gt 0 ] 2>/dev/null; then
            echo $(( (window - tokens) * 100 / window ))
            return
        fi
    done
    echo ""
}

CONTEXT_PCT=$(get_context_pct)

# Fallback: tool-call-count estimate (~180 calls ≈ 100% context)
if [ -z "$CONTEXT_PCT" ]; then
    CONTEXT_PCT=$(( 100 - (COUNT * 100 / 180) ))
    [ "$CONTEXT_PCT" -lt 0 ] && CONTEXT_PCT=0
    SOURCE="estimate"
else
    SOURCE="debug"
fi

echo "$CONTEXT_PCT" > "$PCT_FILE"

TIMESTAMP=$(date '+%Y-%m-%d %H:%M')

generate_evacuation_template() {
    local level="$1"

    if [ -f "$EVAC_COOLDOWN_FILE" ]; then
        local last_ts now_ts
        last_ts=$(cat "$EVAC_COOLDOWN_FILE" 2>/dev/null || echo 0)
        now_ts=$(date +%s)
        [ $(( now_ts - last_ts )) -lt "$EVAC_COOLDOWN_SEC" ] && return
    fi

    # Skip if an unfilled template already exists
    if [ -f "$MISSION_FILE" ] && grep -q '\[TODO\]' "$MISSION_FILE" 2>/dev/null; then
        return
    fi

    date +%s > "$EVAC_COOLDOWN_FILE"
    mkdir -p "$(dirname "$MISSION_FILE")"

    cat >> "$MISSION_FILE" << EVAC_EOF

## Context Evacuation (${level} — ${TIMESTAMP})
<!-- Auto-generated by context-monitor.sh. Fill before /compact. -->

### Job state
- Job ID: ${CIC_JOB_ID}
- Feature branch: feature/${CIC_JOB_ID}
- Current task: [TODO]
- Progress: [TODO]
- Files being edited: [TODO]

### Git state
- Uncommitted changes: [TODO]
- Last commit: [TODO]

### Next action after /compact
- [TODO]

### Handoff
- Commit output/ with: git -C ${CIC_WORKDIR}/jobs/${CIC_JOB_ID}/workspace/cic-factory commit -m "job: ${CIC_JOB_ID} — partial"
EVAC_EOF
}

if [ "$CONTEXT_PCT" -le 15 ]; then
    if [ "$LAST_STATE" != "emergency" ]; then
        echo "emergency" > "$STATE_FILE"
        generate_evacuation_template "EMERGENCY"
    fi
    echo ""
    echo "EMERGENCY [CIC]: Context remaining ${CONTEXT_PCT}% (${SOURCE}) — job: ${CIC_JOB_ID}"
    echo "1. Commit all output/ changes immediately"
    echo "2. Run /compact"
    echo "3. Resume from context-state.md: ${MISSION_FILE}"
    echo "No further work. Commit and compact only."

elif [ "$CONTEXT_PCT" -le 20 ]; then
    if [ "$LAST_STATE" != "critical" ]; then
        echo "critical" > "$STATE_FILE"
        generate_evacuation_template "CRITICAL"
    fi
    echo ""
    echo "CRITICAL [CIC]: Context remaining ${CONTEXT_PCT}% (${SOURCE}) — job: ${CIC_JOB_ID}"
    echo "Finish current file, commit output/, then run /compact."

elif [ "$CONTEXT_PCT" -le 25 ]; then
    if [ "$LAST_STATE" != "warning" ]; then
        echo "warning" > "$STATE_FILE"
        echo ""
        echo "WARNING [CIC]: Context remaining ${CONTEXT_PCT}% (${SOURCE}) — job: ${CIC_JOB_ID}"
        echo "Do not start new large tasks. Wrap up and save state."
    fi

elif [ "$CONTEXT_PCT" -le 40 ]; then
    if [ "$LAST_STATE" != "caution" ]; then
        echo "caution" > "$STATE_FILE"
        echo ""
        echo "CAUTION [CIC]: Context remaining ${CONTEXT_PCT}% (${SOURCE}) — job: ${CIC_JOB_ID}"
        echo "Be concise. Prefer targeted reads over full-file reads."
    fi
fi

exit 0
