#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileCopyrightText: 2025-2026 Sinkó Gábor Zoltán / CentralInfraCore
# Generates jobs/index.yaml from all jobs/*/meta.yaml files
set -euo pipefail

WORKDIR="$(cd "$(dirname "$0")/.." && pwd)"
INDEX="$WORKDIR/jobs/index.yaml"

python3 - "$WORKDIR" <<'PYEOF'
import os, sys
import re
from datetime import datetime, timezone

workdir = sys.argv[1]
jobs_dir = os.path.join(workdir, "jobs")

def read_field(content, field, default=""):
    m = re.search(rf'^{field}:\s*"?([^"\n]+)"?', content, re.MULTILINE)
    return m.group(1).strip() if m else default

def read_nested(content, field, default=""):
    m = re.search(rf'^\s+{field}:\s*"?([^"\n]+)"?', content, re.MULTILINE)
    return m.group(1).strip() if m else default

jobs = []
for entry in sorted(os.listdir(jobs_dir)):
    if entry.startswith("."):
        continue
    meta_path = os.path.join(jobs_dir, entry, "meta.yaml")
    if not os.path.isfile(meta_path):
        continue
    with open(meta_path) as f:
        content = f.read()
    jobs.append({
        "id":        read_field(content, "job_id"),
        "level":     read_field(content, "level"),
        "status":    read_field(content, "status"),
        "parent":    read_field(content, "parent_job_id"),
        "created":   read_nested(content, "created"),
        "started":   read_nested(content, "started"),
        "completed": read_nested(content, "completed"),
        "repo":      read_nested(content, "repo"),
        "model":     read_nested(content, "model"),
        "cost_usd":  read_nested(content, "cost_usd"),
        "turns":     read_nested(content, "turns"),
    })

now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
lines = [f"# Auto-generated by tools/update-index.sh — {now}", "jobs:"]
for j in jobs:
    lines.append(f"  - id: \"{j['id']}\"")
    lines.append(f"    level: \"{j['level']}\"")
    lines.append(f"    status: \"{j['status']}\"")
    if j["parent"]:
        lines.append(f"    parent: \"{j['parent']}\"")
    if j["repo"]:
        lines.append(f"    target_repo: \"{j['repo']}\"")
    lines.append(f"    created: \"{j['created']}\"")
    if j["started"]:
        lines.append(f"    started: \"{j['started']}\"")
    if j["completed"]:
        lines.append(f"    completed: \"{j['completed']}\"")
    if j["model"]:
        lines.append(f"    model: \"{j['model']}\"")
    if j["cost_usd"]:
        lines.append(f"    cost_usd: \"{j['cost_usd']}\"")
    if j["turns"]:
        lines.append(f"    turns: \"{j['turns']}\"")

# Cost roll-up — makes the model-layering effect measurable rather than assumed
total = 0.0
priced = 0
for j in jobs:
    try:
        total += float(j["cost_usd"])
        priced += 1
    except (TypeError, ValueError):
        pass
lines.append("")
lines.append("totals:")
lines.append(f"  jobs: {len(jobs)}")
lines.append(f"  priced_jobs: {priced}")
lines.append(f"  cost_usd: \"{total:.4f}\"")

index_path = os.path.join(jobs_dir, "index.yaml")
with open(index_path, "w") as f:
    f.write("\n".join(lines) + "\n")
print(f"Index updated: {len(jobs)} job(s), {priced} with cost data, total ${total:.4f}")
PYEOF
